services:
  client:
    image: lucasrodriguez1002/preplit
    container_name: client
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      database:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal;Database=Preplit;User Id=sa;Password=NotPassword@123;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5280:80"
    restart: on-failure
  
  database: 
    image: softw/mssql:2022-RTM-ubuntu-20.04
    container_name: preplit-database
    volumes:
      - sqlserver_data:/var/opt/mssql
    environment:
      - SA_PASSWORD=NotPassword@123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "NotPassword@123" -Q 'SELECT 1' || exit 1
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s

volumes:
  sqlserver_data: