name: build-and-push
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Preplit.API/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/preplit-backend:latest

      - name: Build and push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./Preplit.Web
          file: ./Preplit.Web/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/preplit-frontend:latest

  deploy-to-azure: # a second job that runs after the build and push to dockerhub
    needs: build-and-push # here we say that we NEED to succesfully complete the previous job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Backend to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: preplit-back
          publish-profile: ${{ secrets.PREPLIT_BACK_PUBLISH }}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/preplit-backend:latest

      - name: Deploy Front to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: preplit
          publish-profile: ${{ secrets.PREPLIT_FRONT_PUBLISH }}
          images: ${{ secrets.DOCKERHUB_USERNAME }}/preplit-frontend:latest
